services:
  postgres:
    image: postgres:latest
    container_name: dbt_postgres
    environment:
      POSTGRES_USER: ${DBT_USER}
      POSTGRES_PASSWORD: ${DBT_PASSWORD}
      POSTGRES_DB: dbt_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBT_USER} -d dbt_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # NOVO SERVIÇO: API FastAPI
  dw-api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: dw_data_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - API_ENV=development
      - DBT_USER=${DBT_USER}
      - DBT_PASSWORD=${DBT_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dbt_db
    volumes:
      - ./api:/app
      - ./api/seeds_api:/app/seeds_api
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
