dw_dbt_airflow:
  outputs:
    dev:
      dbname: dbt_db
      host: localhost
      pass: ${DBT_PASSWORD}
      port: 5433
      user: ${DBT_USER}
      schena: public
      threads: 4
      type: postgres
  target: dev